baseURL = 'https://blog.pierrebeaujean.net'
languageCode = 'en-us'
title = "Pierre Beaujean's blog"
theme = 'archie'
copyright = "© Pierre Beaujean"

paginate = 5

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
mode="toggle" # color-mode → light,dark,toggle or auto
subtitle = "Quantum Chemistry, programming, random thoughts, & stuffs. *Parfois en français*."
katex = true # enable KaTeX support

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/pierre-24/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/PierreBeaujean"


[[menu.main]]
name = "All posts"
url = "/posts"
weight = 1

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 2

[[menu.main]]
name = "About me"
url = "https://pierrebeaujean.net"
weight = 3
